### ISSUE TITLE
改了好多啊

### ISSUE THREAD

**Issue by H-704** [412LEGEND/Homepage#8]
> 我觉得是不是应该分一个简体中文版的和一个英语版的呢？

**Comment by SketchySketch** [comment]
当然可以。。。可是好麻烦啊。。。算了吧。。。反正我们都看得懂。。。

**Comment by H-704** [comment]
那可真是神奇啊

**Comment by SketchySketch** [comment]
？
在2020年04月13日 13:53，Hu Yichen 写道：

那可真是神奇啊
